name: Pull Request Check # 워크플로우 이름

on: # 워크플로우 실행 트리거
   pull_request: # PR이 실행될 때만 동작
      types: [opened, synchronize] # PR 생성 및 업데이트 시

jobs: # 작업 정의
   check:
      runs-on: ubuntu-latest # GitHub Action이 실행되는 환경
      permissions: # 권한 설정
         pull-requests: write # PR 쓰기 권한 설정
      steps: # 작업 단계
         - name: Check PR Body
           uses: actions/github-script@v7
           with:
              script: |
                 const pull_request = context.payload.pull_request;

                 if (!pull_request) {
                   console.log("This is not a pull request");
                   return;
                 }

                 const body = pull_request.body;

                 const message = "아래 내용을 작성하고, 이 문구를 삭제해 주세요."

                 if (!body || body.includes(message)) {
                   // PR에 코멘트 추가
                   await github.rest.issues.createComment({
                     owner: context.repo.owner, // 저장소 소유자
                     repo: context.repo.repo, // 저장소 이름
                     issue_number: pull_request.number, // PR 번호
                     body: "가이드 라인을 확인하여 다시 PR을 요청해주세요. 해당 PR을 닫겠습니다.", // 코멘트 내용
                   });

                   // PR 닫기
                   await github.rest.pulls.update({
                     owner: context.repo.owner, // 저장소 소유자
                     repo: context.repo.repo, // 저장소 이름
                     pull_number: pull_request.number, // PR 번호
                     state: "closed", // 상태를 닫힘으로 변경
                   });
                 }
